// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_repo is a generated GoMock package.
package repo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	course "github.com/ozonva/ova-course-api/internal/course"
)

// MockCourseRepo is a mock of CourseRepo interface.
type MockCourseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCourseRepoMockRecorder
}

// MockCourseRepoMockRecorder is the mock recorder for MockCourseRepo.
type MockCourseRepoMockRecorder struct {
	mock *MockCourseRepo
}

// NewMockCourseRepo creates a new mock instance.
func NewMockCourseRepo(ctrl *gomock.Controller) *MockCourseRepo {
	mock := &MockCourseRepo{ctrl: ctrl}
	mock.recorder = &MockCourseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseRepo) EXPECT() *MockCourseRepoMockRecorder {
	return m.recorder
}

// AddCourse mocks base method.
func (m *MockCourseRepo) AddCourse(entities []course.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCourse", entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCourse indicates an expected call of AddCourse.
func (mr *MockCourseRepoMockRecorder) AddCourse(entities []course.Course) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCourse", reflect.TypeOf((*MockCourseRepo)(nil).AddCourse), entities)
}

// DescribeCourses mocks base method.
func (m *MockCourseRepo) DescribeCourses(entityId uint64) (*course.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeCourses", entityId)
	ret0, _ := ret[0].(*course.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeCourses indicates an expected call of DescribeCourses.
func (mr *MockCourseRepoMockRecorder) DescribeCourses(entityId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeCourses", reflect.TypeOf((*MockCourseRepo)(nil).DescribeCourses), entityId)
}

// ListCourses mocks base method.
func (m *MockCourseRepo) ListCourses(limit, offset uint64) ([]course.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCourses", limit, offset)
	ret0, _ := ret[0].([]course.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCourses indicates an expected call of ListCourses.
func (mr *MockCourseRepoMockRecorder) ListCourses(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCourses", reflect.TypeOf((*MockCourseRepo)(nil).ListCourses), limit, offset)
}
